# Generated by Django 2.0.5 on 2018-06-22 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=253, verbose_name='微信openid')),
                ('nick_name', models.CharField(max_length=253, verbose_name='昵称')),
                ('avatar_url', models.CharField(max_length=253, verbose_name='用户头像')),
                ('gender', models.CharField(choices=[(0, '未知'), (1, '男'), (2, '女')], max_length=253, verbose_name='性别')),
                ('city', models.CharField(max_length=253, verbose_name='所在城市')),
                ('province', models.CharField(max_length=253, verbose_name='所在省份')),
                ('country', models.CharField(max_length=253, verbose_name='所在国家')),
                ('language', models.CharField(max_length=253, verbose_name='用户的语言')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '微信',
                'verbose_name_plural': '微信',
            },
        ),
    ]
